language: node_js

services:
  - docker

before_install:
  - docker build -t "${IMAGE_NAME}:ci" .
  - curl -s "https://raw.githubusercontent.com/anchore/ci-tools/stateless_ci_container/scripts/inline_scan" | bash -s -- -r "${IMAGE_NAME}:ci"
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push "${IMAGE_NAME}:${IMAGE_TAG}"