version: 0.2

phases:
  build:
    commands:
      - docker build -t $IMAGE_NAME:$IMAGE_TAG .

  post_build:
    commands:
      - curl -s https://ci-tools.anchore.io/inline_scan-v0.3.3 | bash -s -- ${IMAGE_NAME}:$IMAGE_TAG
      - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - docker push $IMAGE_NAME:$IMAGE_TAG